# Generated by Django 5.1.4 on 2025-02-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("lat", models.CharField(max_length=255)),
                ("lon", models.CharField(max_length=255)),
                ("weather_overview", models.TextField(blank=True)),
                ("temperature", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
